---

- name: stat tokens/cluster_name.yml
  stat:
    path:  cfg/{{ cluster_name }}/token.yml
  register: token_file

- import_tasks: retrieve_token.yml
  when: token_file.stat.exists

- import_tasks: generate_token.yml
  when: not token_file.stat.exists
